/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.stopwatch;

import fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.IStatemachine;

public interface IStopwatchStatemachine extends IStatemachine {
	public interface SCInterface {
	
		public void raiseRBt();
		
		public void raiseLBt();
		
		public boolean isRaisedDoInitial();
		
		public boolean isRaisedDoStart();
		
		public boolean isRaisedDoPause();
		
		public boolean isRaisedDoResume();
		
		public boolean isRaisedDoStop();
		
	}
	
	public SCInterface getSCInterface();
	
}
