/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.stopwatch;

import fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IStopwatchStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseRBt();
		
		public void raiseLBt();
		
		public void raiseMBt();
		
		public void raiseM2Bt();
		
		public boolean isRaisedDoInitial();
		
		public boolean isRaisedDoStart();
		
		public boolean isRaisedDoPause();
		
		public boolean isRaisedDoResume();
		
		public boolean isRaisedDoStop();
		
		public boolean isRaisedDoHour();
		
		public boolean isRaisedDoDate();
		
		public boolean isRaisedDoClearTitle();
		
		public boolean isRaisedDoRecord();
		
		public boolean isRaisedDoChangeButtonName();
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoInitialRaised();
		public void onDoStartRaised();
		public void onDoPauseRaised();
		public void onDoResumeRaised();
		public void onDoStopRaised();
		public void onDoHourRaised();
		public void onDoDateRaised();
		public void onDoClearTitleRaised();
		public void onDoRecordRaised();
		public void onDoChangeButtonNameRaised();
		}
	
	public SCInterface getSCInterface();
	
}
