/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.stopwatch;


public class StopwatchStatemachine implements IStopwatchStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private boolean rBt;
		
		
		public void raiseRBt() {
			rBt = true;
			runCycle();
		}
		
		private boolean lBt;
		
		
		public void raiseLBt() {
			lBt = true;
			runCycle();
		}
		
		private boolean doInitial;
		
		
		public boolean isRaisedDoInitial() {
			return doInitial;
		}
		
		protected void raiseDoInitial() {
			doInitial = true;
		}
		
		private boolean doStart;
		
		
		public boolean isRaisedDoStart() {
			return doStart;
		}
		
		protected void raiseDoStart() {
			doStart = true;
		}
		
		private boolean doPause;
		
		
		public boolean isRaisedDoPause() {
			return doPause;
		}
		
		protected void raiseDoPause() {
			doPause = true;
		}
		
		private boolean doResume;
		
		
		public boolean isRaisedDoResume() {
			return doResume;
		}
		
		protected void raiseDoResume() {
			doResume = true;
		}
		
		private boolean doStop;
		
		
		public boolean isRaisedDoStop() {
			return doStop;
		}
		
		protected void raiseDoStop() {
			doStop = true;
		}
		
		protected void clearEvents() {
			rBt = false;
			lBt = false;
		}
		protected void clearOutEvents() {
		
		doInitial = false;
		doStart = false;
		doPause = false;
		doResume = false;
		doStop = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_StateStart,
		main_region_StatePause,
		main_region_StateStop,
		main_region_StateInitial,
		main_region_StateResume,
		$NullState$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	public StopwatchStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		enterSequence_main_region_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_StateStart:
				main_region_StateStart_react(true);
				break;
			case main_region_StatePause:
				main_region_StatePause_react(true);
				break;
			case main_region_StateStop:
				main_region_StateStop_react(true);
				break;
			case main_region_StateInitial:
				main_region_StateInitial_react(true);
				break;
			case main_region_StateResume:
				main_region_StateResume_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_StateStart:
			return stateVector[0] == State.main_region_StateStart;
		case main_region_StatePause:
			return stateVector[0] == State.main_region_StatePause;
		case main_region_StateStop:
			return stateVector[0] == State.main_region_StateStop;
		case main_region_StateInitial:
			return stateVector[0] == State.main_region_StateInitial;
		case main_region_StateResume:
			return stateVector[0] == State.main_region_StateResume;
		default:
			return false;
		}
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public void raiseRBt() {
		sCInterface.raiseRBt();
	}
	
	public void raiseLBt() {
		sCInterface.raiseLBt();
	}
	
	public boolean isRaisedDoInitial() {
		return sCInterface.isRaisedDoInitial();
	}
	
	public boolean isRaisedDoStart() {
		return sCInterface.isRaisedDoStart();
	}
	
	public boolean isRaisedDoPause() {
		return sCInterface.isRaisedDoPause();
	}
	
	public boolean isRaisedDoResume() {
		return sCInterface.isRaisedDoResume();
	}
	
	public boolean isRaisedDoStop() {
		return sCInterface.isRaisedDoStop();
	}
	
	/* Entry action for state 'StateStart'. */
	private void entryAction_main_region_StateStart() {
		sCInterface.raiseDoStart();
	}
	
	/* Entry action for state 'StatePause'. */
	private void entryAction_main_region_StatePause() {
		sCInterface.raiseDoPause();
	}
	
	/* Entry action for state 'StateStop'. */
	private void entryAction_main_region_StateStop() {
		sCInterface.raiseDoStop();
	}
	
	/* Entry action for state 'StateInitial'. */
	private void entryAction_main_region_StateInitial() {
		sCInterface.raiseDoInitial();
	}
	
	/* Entry action for state 'StateResume'. */
	private void entryAction_main_region_StateResume() {
		sCInterface.raiseDoResume();
	}
	
	/* 'default' enter sequence for state StateStart */
	private void enterSequence_main_region_StateStart_default() {
		entryAction_main_region_StateStart();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_StateStart;
	}
	
	/* 'default' enter sequence for state StatePause */
	private void enterSequence_main_region_StatePause_default() {
		entryAction_main_region_StatePause();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_StatePause;
	}
	
	/* 'default' enter sequence for state StateStop */
	private void enterSequence_main_region_StateStop_default() {
		entryAction_main_region_StateStop();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_StateStop;
	}
	
	/* 'default' enter sequence for state StateInitial */
	private void enterSequence_main_region_StateInitial_default() {
		entryAction_main_region_StateInitial();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_StateInitial;
	}
	
	/* 'default' enter sequence for state StateResume */
	private void enterSequence_main_region_StateResume_default() {
		entryAction_main_region_StateResume();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_StateResume;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* Default exit sequence for state StateStart */
	private void exitSequence_main_region_StateStart() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StatePause */
	private void exitSequence_main_region_StatePause() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StateStop */
	private void exitSequence_main_region_StateStop() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StateInitial */
	private void exitSequence_main_region_StateInitial() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StateResume */
	private void exitSequence_main_region_StateResume() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_StateStart:
			exitSequence_main_region_StateStart();
			break;
		case main_region_StatePause:
			exitSequence_main_region_StatePause();
			break;
		case main_region_StateStop:
			exitSequence_main_region_StateStop();
			break;
		case main_region_StateInitial:
			exitSequence_main_region_StateInitial();
			break;
		case main_region_StateResume:
			exitSequence_main_region_StateResume();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_StateInitial_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_StateStart_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.rBt) {
				exitSequence_main_region_StateStart();
				enterSequence_main_region_StatePause_default();
				react();
			} else {
				if (sCInterface.lBt) {
					exitSequence_main_region_StateStart();
					enterSequence_main_region_StateStop_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_StatePause_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.lBt) {
				exitSequence_main_region_StatePause();
				enterSequence_main_region_StateStop_default();
				react();
			} else {
				if (sCInterface.rBt) {
					exitSequence_main_region_StatePause();
					enterSequence_main_region_StateResume_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_StateStop_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.lBt) {
				exitSequence_main_region_StateStop();
				enterSequence_main_region_StateInitial_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_StateInitial_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.lBt) {
				exitSequence_main_region_StateInitial();
				enterSequence_main_region_StateStart_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_StateResume_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.lBt) {
				exitSequence_main_region_StateResume();
				enterSequence_main_region_StateStop_default();
				react();
			} else {
				if (sCInterface.rBt) {
					exitSequence_main_region_StateResume();
					enterSequence_main_region_StatePause_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
}
