/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.stopwatch;

import fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.ITimer;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class StopwatchStatemachine implements IStopwatchStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean rBt;
		
		
		public void raiseRBt() {
			synchronized(StopwatchStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							rBt = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean lBt;
		
		
		public void raiseLBt() {
			synchronized(StopwatchStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							lBt = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean mBt;
		
		
		public void raiseMBt() {
			synchronized(StopwatchStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							mBt = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean doInitial;
		
		
		public boolean isRaisedDoInitial() {
			synchronized(StopwatchStatemachine.this) {
				return doInitial;
			}
		}
		
		protected void raiseDoInitial() {
			synchronized(StopwatchStatemachine.this) {
				doInitial = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoInitialRaised();
				}
			}
		}
		
		private boolean doStart;
		
		
		public boolean isRaisedDoStart() {
			synchronized(StopwatchStatemachine.this) {
				return doStart;
			}
		}
		
		protected void raiseDoStart() {
			synchronized(StopwatchStatemachine.this) {
				doStart = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoStartRaised();
				}
			}
		}
		
		private boolean doPause;
		
		
		public boolean isRaisedDoPause() {
			synchronized(StopwatchStatemachine.this) {
				return doPause;
			}
		}
		
		protected void raiseDoPause() {
			synchronized(StopwatchStatemachine.this) {
				doPause = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoPauseRaised();
				}
			}
		}
		
		private boolean doResume;
		
		
		public boolean isRaisedDoResume() {
			synchronized(StopwatchStatemachine.this) {
				return doResume;
			}
		}
		
		protected void raiseDoResume() {
			synchronized(StopwatchStatemachine.this) {
				doResume = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoResumeRaised();
				}
			}
		}
		
		private boolean doStop;
		
		
		public boolean isRaisedDoStop() {
			synchronized(StopwatchStatemachine.this) {
				return doStop;
			}
		}
		
		protected void raiseDoStop() {
			synchronized(StopwatchStatemachine.this) {
				doStop = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoStopRaised();
				}
			}
		}
		
		private boolean doHour;
		
		
		public boolean isRaisedDoHour() {
			synchronized(StopwatchStatemachine.this) {
				return doHour;
			}
		}
		
		protected void raiseDoHour() {
			synchronized(StopwatchStatemachine.this) {
				doHour = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoHourRaised();
				}
			}
		}
		
		private boolean doDate;
		
		
		public boolean isRaisedDoDate() {
			synchronized(StopwatchStatemachine.this) {
				return doDate;
			}
		}
		
		protected void raiseDoDate() {
			synchronized(StopwatchStatemachine.this) {
				doDate = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoDateRaised();
				}
			}
		}
		
		private boolean doClearTitle;
		
		
		public boolean isRaisedDoClearTitle() {
			synchronized(StopwatchStatemachine.this) {
				return doClearTitle;
			}
		}
		
		protected void raiseDoClearTitle() {
			synchronized(StopwatchStatemachine.this) {
				doClearTitle = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoClearTitleRaised();
				}
			}
		}
		
		private boolean doRecord;
		
		
		public boolean isRaisedDoRecord() {
			synchronized(StopwatchStatemachine.this) {
				return doRecord;
			}
		}
		
		protected void raiseDoRecord() {
			synchronized(StopwatchStatemachine.this) {
				doRecord = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoRecordRaised();
				}
			}
		}
		
		private boolean doChangeButtonName;
		
		
		public boolean isRaisedDoChangeButtonName() {
			synchronized(StopwatchStatemachine.this) {
				return doChangeButtonName;
			}
		}
		
		protected void raiseDoChangeButtonName() {
			synchronized(StopwatchStatemachine.this) {
				doChangeButtonName = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoChangeButtonNameRaised();
				}
			}
		}
		
		protected void clearEvents() {
			rBt = false;
			lBt = false;
			mBt = false;
		}
		protected void clearOutEvents() {
		
		doInitial = false;
		doStart = false;
		doPause = false;
		doResume = false;
		doStop = false;
		doHour = false;
		doDate = false;
		doClearTitle = false;
		doRecord = false;
		doChangeButtonName = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_watch,
		main_region_watch_r1_StatePause,
		main_region_watch_r1_StateStart,
		main_region_watch_r1_StateResume,
		main_region_watch_r1_StateStop,
		main_region_watch_r1_StateInitial,
		main_region_watch_record_StateRecord,
		main_region_watch_record_StateIntial,
		$NullState$
	};
	
	private final State[] stateVector = new State[2];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[1];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	public StopwatchStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 2; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_watch_r1_StatePause:
				main_region_watch_r1_StatePause_react(true);
				break;
			case main_region_watch_r1_StateStart:
				main_region_watch_r1_StateStart_react(true);
				break;
			case main_region_watch_r1_StateResume:
				main_region_watch_r1_StateResume_react(true);
				break;
			case main_region_watch_r1_StateStop:
				main_region_watch_r1_StateStop_react(true);
				break;
			case main_region_watch_r1_StateInitial:
				main_region_watch_r1_StateInitial_react(true);
				break;
			case main_region_watch_record_StateRecord:
				main_region_watch_record_StateRecord_react(true);
				break;
			case main_region_watch_record_StateIntial:
				main_region_watch_record_StateIntial_react(true);
				break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_watch:
			return stateVector[0].ordinal() >= State.
					main_region_watch.ordinal()&& stateVector[0].ordinal() <= State.main_region_watch_record_StateIntial.ordinal();
		case main_region_watch_r1_StatePause:
			return stateVector[0] == State.main_region_watch_r1_StatePause;
		case main_region_watch_r1_StateStart:
			return stateVector[0] == State.main_region_watch_r1_StateStart;
		case main_region_watch_r1_StateResume:
			return stateVector[0] == State.main_region_watch_r1_StateResume;
		case main_region_watch_r1_StateStop:
			return stateVector[0] == State.main_region_watch_r1_StateStop;
		case main_region_watch_r1_StateInitial:
			return stateVector[0] == State.main_region_watch_r1_StateInitial;
		case main_region_watch_record_StateRecord:
			return stateVector[1] == State.main_region_watch_record_StateRecord;
		case main_region_watch_record_StateIntial:
			return stateVector[1] == State.main_region_watch_record_StateIntial;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
				singleCycle();
			}
		});
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public synchronized void raiseRBt() {
		sCInterface.raiseRBt();
	}
	
	public synchronized void raiseLBt() {
		sCInterface.raiseLBt();
	}
	
	public synchronized void raiseMBt() {
		sCInterface.raiseMBt();
	}
	
	public synchronized boolean isRaisedDoInitial() {
		return sCInterface.isRaisedDoInitial();
	}
	
	public synchronized boolean isRaisedDoStart() {
		return sCInterface.isRaisedDoStart();
	}
	
	public synchronized boolean isRaisedDoPause() {
		return sCInterface.isRaisedDoPause();
	}
	
	public synchronized boolean isRaisedDoResume() {
		return sCInterface.isRaisedDoResume();
	}
	
	public synchronized boolean isRaisedDoStop() {
		return sCInterface.isRaisedDoStop();
	}
	
	public synchronized boolean isRaisedDoHour() {
		return sCInterface.isRaisedDoHour();
	}
	
	public synchronized boolean isRaisedDoDate() {
		return sCInterface.isRaisedDoDate();
	}
	
	public synchronized boolean isRaisedDoClearTitle() {
		return sCInterface.isRaisedDoClearTitle();
	}
	
	public synchronized boolean isRaisedDoRecord() {
		return sCInterface.isRaisedDoRecord();
	}
	
	public synchronized boolean isRaisedDoChangeButtonName() {
		return sCInterface.isRaisedDoChangeButtonName();
	}
	
	/* Entry action for state 'StatePause'. */
	private void entryAction_main_region_watch_r1_StatePause() {
		sCInterface.raiseDoPause();
	}
	
	/* Entry action for state 'StateStart'. */
	private void entryAction_main_region_watch_r1_StateStart() {
		sCInterface.raiseDoStart();
	}
	
	/* Entry action for state 'StateResume'. */
	private void entryAction_main_region_watch_r1_StateResume() {
		sCInterface.raiseDoResume();
	}
	
	/* Entry action for state 'StateStop'. */
	private void entryAction_main_region_watch_r1_StateStop() {
		sCInterface.raiseDoStop();
	}
	
	/* Entry action for state 'StateInitial'. */
	private void entryAction_main_region_watch_r1_StateInitial() {
		sCInterface.raiseDoInitial();
	}
	
	/* Entry action for state 'StateRecord'. */
	private void entryAction_main_region_watch_record_StateRecord() {
		timer.setTimer(this, 0, (1 * 1000), false);
		
		sCInterface.raiseDoRecord();
	}
	
	/* Exit action for state 'StateRecord'. */
	private void exitAction_main_region_watch_record_StateRecord() {
		timer.unsetTimer(this, 0);
	}
	
	/* 'default' enter sequence for state watch */
	private void enterSequence_main_region_watch_default() {
		enterSequence_main_region_watch_r1_default();
		enterSequence_main_region_watch_record_default();
	}
	
	/* 'default' enter sequence for state StatePause */
	private void enterSequence_main_region_watch_r1_StatePause_default() {
		entryAction_main_region_watch_r1_StatePause();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_watch_r1_StatePause;
	}
	
	/* 'default' enter sequence for state StateStart */
	private void enterSequence_main_region_watch_r1_StateStart_default() {
		entryAction_main_region_watch_r1_StateStart();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_watch_r1_StateStart;
	}
	
	/* 'default' enter sequence for state StateResume */
	private void enterSequence_main_region_watch_r1_StateResume_default() {
		entryAction_main_region_watch_r1_StateResume();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_watch_r1_StateResume;
	}
	
	/* 'default' enter sequence for state StateStop */
	private void enterSequence_main_region_watch_r1_StateStop_default() {
		entryAction_main_region_watch_r1_StateStop();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_watch_r1_StateStop;
	}
	
	/* 'default' enter sequence for state StateInitial */
	private void enterSequence_main_region_watch_r1_StateInitial_default() {
		entryAction_main_region_watch_r1_StateInitial();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_watch_r1_StateInitial;
	}
	
	/* 'default' enter sequence for state StateRecord */
	private void enterSequence_main_region_watch_record_StateRecord_default() {
		entryAction_main_region_watch_record_StateRecord();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_watch_record_StateRecord;
	}
	
	/* 'default' enter sequence for state StateIntial */
	private void enterSequence_main_region_watch_record_StateIntial_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_watch_record_StateIntial;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_watch_r1_default() {
		react_main_region_watch_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region record */
	private void enterSequence_main_region_watch_record_default() {
		react_main_region_watch_record__entry_Default();
	}
	
	/* Default exit sequence for state StatePause */
	private void exitSequence_main_region_watch_r1_StatePause() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StateStart */
	private void exitSequence_main_region_watch_r1_StateStart() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StateResume */
	private void exitSequence_main_region_watch_r1_StateResume() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StateStop */
	private void exitSequence_main_region_watch_r1_StateStop() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StateInitial */
	private void exitSequence_main_region_watch_r1_StateInitial() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state StateRecord */
	private void exitSequence_main_region_watch_record_StateRecord() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_watch_record_StateRecord();
	}
	
	/* Default exit sequence for state StateIntial */
	private void exitSequence_main_region_watch_record_StateIntial() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_watch_r1_StatePause:
			exitSequence_main_region_watch_r1_StatePause();
			break;
		case main_region_watch_r1_StateStart:
			exitSequence_main_region_watch_r1_StateStart();
			break;
		case main_region_watch_r1_StateResume:
			exitSequence_main_region_watch_r1_StateResume();
			break;
		case main_region_watch_r1_StateStop:
			exitSequence_main_region_watch_r1_StateStop();
			break;
		case main_region_watch_r1_StateInitial:
			exitSequence_main_region_watch_r1_StateInitial();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_watch_record_StateRecord:
			exitSequence_main_region_watch_record_StateRecord();
			break;
		case main_region_watch_record_StateIntial:
			exitSequence_main_region_watch_record_StateIntial();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_watch_r1__entry_Default() {
		enterSequence_main_region_watch_r1_StateInitial_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_watch_record__entry_Default() {
		enterSequence_main_region_watch_record_StateIntial_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_watch_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_watch_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_watch_r1_StatePause_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.lBt) {
				exitSequence_main_region_watch_r1_StatePause();
				enterSequence_main_region_watch_r1_StateStop_default();
			} else {
				if (sCInterface.rBt) {
					exitSequence_main_region_watch_r1_StatePause();
					enterSequence_main_region_watch_r1_StateResume_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_watch_r1_StateStart_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.rBt) {
				exitSequence_main_region_watch_r1_StateStart();
				enterSequence_main_region_watch_r1_StatePause_default();
			} else {
				if (sCInterface.lBt) {
					exitSequence_main_region_watch_r1_StateStart();
					enterSequence_main_region_watch_r1_StateStop_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_watch_r1_StateResume_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.lBt) {
				exitSequence_main_region_watch_r1_StateResume();
				enterSequence_main_region_watch_r1_StateStop_default();
			} else {
				if (sCInterface.rBt) {
					exitSequence_main_region_watch_r1_StateResume();
					enterSequence_main_region_watch_r1_StatePause_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_watch_r1_StateStop_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.lBt) {
				exitSequence_main_region_watch_r1_StateStop();
				enterSequence_main_region_watch_r1_StateInitial_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_watch_r1_StateInitial_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.lBt) {
				exitSequence_main_region_watch_r1_StateInitial();
				enterSequence_main_region_watch_r1_StateStart_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_watch_record_StateRecord_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.mBt) {
				exitSequence_main_region_watch_record_StateRecord();
				sCInterface.raiseDoClearTitle();
				
				enterSequence_main_region_watch_record_StateIntial_default();
				main_region_watch_react(false);
			} else {
				if (timeEvents[0]) {
					exitSequence_main_region_watch_record_StateRecord();
					sCInterface.raiseDoChangeButtonName();
					
					enterSequence_main_region_watch_record_StateIntial_default();
					main_region_watch_react(false);
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_watch_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_watch_record_StateIntial_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.mBt) {
				exitSequence_main_region_watch_record_StateIntial();
				enterSequence_main_region_watch_record_StateRecord_default();
				main_region_watch_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_watch_react(try_transition);
		}
		return did_transition;
	}
	
}
